{
    "Items": [
        {
            "ID": 0,
            "HumanReadableName": "NONE",
            "TowerDescription": "THIS IS A NULL TOWER VALUE AND NEVER USED BUT NEEDS TO STAY HERE!",
            "HardData": "Hard Nmbers go here!"
        },
        {
            "ID": 1,
            "HumanReadableName": "Acid",
            "TowerDescription": "Sprays acid damage out in small radius around the tower inflicting acid damage over time to those caught in the radius!",
            "HardData": "2 seconds active followed by 3 seconds inactive while active every 0.25 seconds applies 5 seconds of the acid effect to enemies in range."
        },
        {
            "ID": 2,
            "HumanReadableName": "Air",
            "TowerDescription": "Hurl enemies away from the wall with extreme force! Inflicts bludgeoning damage on impact and extra damage to flying enemies!",
            "HardData": "Inflicts 20 impact damage on each enemy. 90 second cool down after use"
        },
        {
            "ID": 4,
            "HumanReadableName": "Ballista",
            "TowerDescription": "Launch a single javelin toward the nearest enemy piercing them!",
            "HardData": "Inflicts 12 Piercing damage per projectile with a fire rate of 1.25 seconds."
        },
        {
            "ID": 5,
            "HumanReadableName": "AcidBallista",
            "TowerDescription": "A bottle of acid replaces the spearhead of the javelin inflicting bludgeoning damage on impact and acid damage over time!",
            "HardData": "Inflicts 10 Bludgeoning damage per projectile with a fire rate of 1.25 seconds. Inflicts acid status effect for 5 seconds"
        },
        {
            "ID": 8,
            "HumanReadableName": "Boost",
            "TowerDescription": "This is Filler Text and should not be seen by players!",
            "HardData": "Inflicts per projectile with a fire rate of 1 seconds."
        },
        {
            "ID": 16,
            "HumanReadableName": "Crystal",
            "TowerDescription": "The crystals here suppress certain abilities of creatures such as healing factors, magic, or spawning enemies on death!",
            "HardData": "Negates enemy special abilities in radius."
        },
        {
            "ID": 32,
            "HumanReadableName": "Earth",
            "TowerDescription": "Summons a wall of earth to block enemies. Given enough impacts they will break through! It will take a short while for the wall to reform. Some enemies may fly over the wall!",
            "HardData": "Has 25 health"
        },
        {
            "ID": 36,
            "HumanReadableName": "SpikedWall",
            "TowerDescription": "The additions of spikes to the earth wall inflict damage on any enemies running into it. Some enemies may fly over the wall!",
            "HardData": "Has 35 health inflicts 7 Piercing damage on colliding enemies."
        },
        {
            "ID": 64,
            "HumanReadableName": "Fire",
            "TowerDescription": "Produces bursts of flame that will ignite nearby enemies inflicting fire damage over time!",
            "HardData": "1 second active followed by 3.5 seconds inactive while active every 0.25 seconds applies 10 seconds of the drain effect to enemies in range."
        },
        {
            "ID": 65,
            "HumanReadableName": "FlamingAcid",
            "TowerDescription": "Spray flaming globules of ignited acidic fuel, coating nearby enemies in acid and igniting them for fire AND acid damage over time!",
            "HardData": "2 seconds active followed by 6 seconds inactive while active every 0.25 seconds applies 5 seconds of the acid effect to enemies in range."
        },
        {
            "ID": 66,
            "HumanReadableName": "Fireball",
            "TowerDescription": "Produce an exploding bomb of fire and air detonating to cause bludgeoning and fire damage in a radius of the impact!",
            "HardData": "Inflicts 35 Fire damage per projectile with a fire rate of 4 seconds."
        },
        {
            "ID": 68,
            "HumanReadableName": "FlamingBallista",
            "TowerDescription": "Fires a superheated metal javelin that ignites enemies and inflicts slightly less piercing damage than a normal ballista!",
            "HardData": "Inflicts 10 Piercing damage per projectile with a fire rate of 1.5 seconds. Inflicts fire status effect for 8 seconds"
        },
        {
            "ID": 576,
            "HumanReadableName": "Frost",
            "TowerDescription": "Creates an inverse endothermic reaction repelling heat in an area causing nearby enemies to be flash frozen and take a small amount of damage.",
            "HardData": "1 second active followed by 3.5 seconds inactive while active every 0.25 seconds applies 9 seconds of the drain effect to enemies in range."
        },
        {
            "ID": 128,
            "HumanReadableName": "Holy",
            "TowerDescription": "Radiant power bursts from the ground particularly effective against the undead!",
            "HardData": "2(5 against undead and fiend) of Holy damage per attack with a fire rate of 1 second."
        },
        {
            "ID": 132,
            "HumanReadableName": "HolyBallista",
            "TowerDescription": "A blessed javelin that is extra effective against undead!",
            "HardData": "10 Holy (if undead or fiend) damage per projectile with a fire rate of 1.5 seconds."
        },
        {
            "ID": 160,
            "HumanReadableName": "HolyEarthenWall",
            "TowerDescription": "This blessed wall will inflict extra damage to undead that run into it. Otherwise acts as a normal earthen wall. Flying enemies will fly over it!",
            "HardData": "Has 25 health inflicts 0 Physical damage on colliding demonic and undead enemies."
        },
        {
            "ID": 256,
            "HumanReadableName": "Light",
            "TowerDescription": "Illuminates hidden enemies such as shadow goblins and increases the bounty for enemies felled in its radius!",
            "HardData": "Boosts reward for enemies killed in radius by 50%."
        },
        {
            "ID": 272,
            "HumanReadableName": "Laser",
            "TowerDescription": "Fires beams of lancing heat that that inflict a hefty amount of fire damage over a short amount of time!",
            "HardData": "Inflicts 7 Fire damage every 0.3 seconds over 1.5 seconds"
        },
        {
            "ID": 512,
            "HumanReadableName": "Repulse",
            "TowerDescription": "Injured enemies will be unable to pass through the repulse barrier! Flying enemies may fly over it!",
            "HardData": "Any non-flying enemies with less than 35% of their health will be repelled."
        },
        {
            "ID": 514,
            "HumanReadableName": "Telekinetic",
            "TowerDescription": "Grab and throw enemies with in its radius(you must actively choose to do so)! Inflicts bludgeoning damage on ground impact, with extra damage to flying enemies.  Requires Activation.",
            "HardData": "Inflicts 7 damages per tile enemy is thrown over."
        },
        {
            "ID": 518,
            "HumanReadableName": "PerpetualBolt",
            "TowerDescription": "Fires a single projectile that will home through multiple enemies before eventually collapsing!",
            "HardData": "Fires a single projectile capable of doing up to 100 Piercing damage. Has a 2 second cool down after previous projectile has expired."
        },
        {
            "ID": 1024,
            "HumanReadableName": "Static",
            "TowerDescription": "Increases the speed of ballista and trebuchet projectiles to help catch enemies before they move out of range!",
            "HardData": "Increase the speed of trebuchet, railgun, and ballista projectiles by 100%."
        },
        {
            "ID": 1026,
            "HumanReadableName": "Lightning",
            "TowerDescription": "Chains together enemies near each other with bursts of lightning damage!",
            "HardData": "Every 3 seconds inflicts 10 Electric damage on up to 7 enemies."
        },
        {
            "ID": 1536,
            "HumanReadableName": "Magnet",
            "TowerDescription": "Grabs enemies and hurls them through the air in the direction of the magnet tower, beware they will overshoot it.",
            "HardData": "Inflicts 20 impact damage on each enemy and flings them towards the tower. 70 second cool down after use"
        },
        {
            "ID": 2048,
            "HumanReadableName": "Trebuchet",
            "TowerDescription": "Hurls an inaccurate but cheap boulder with a small AOE effect for its bludgeoning damage!",
            "HardData": "Inflicts 15 Bludgeoning damage per projectile with a fire rate of 3 seconds.. Inflicts effects in a 1 tile radius at point of impact."
        },
        {
            "ID": 2114,
            "HumanReadableName": "Meteor",
            "TowerDescription": "Tears stones from the heavens to rain fire upon our enemies! Requires Activation.",
            "HardData": "20 Fire damage . 120 second cool down after use"
        },
        {
            "ID": 4128,
            "HumanReadableName": "Mud",
            "TowerDescription": "A patch of ground turns into a mire of mud that swallows non-flying enemies whole.",
            "HardData": "Number of enemies swallowable varies depending on their size. If only dealing with goblins can swallow 15 before needing to reset."
        },
        {
            "ID": 2049,
            "HumanReadableName": "AcidTrebuchet",
            "TowerDescription": "Hurls an inaccurate bottle of acid that inflicts bludgeoning damage in a small radius on impact and coats nearby enemies in acid for acid damage over time!",
            "HardData": "Inflicts 15 Bludgeoning damage per projectile with a fire rate of 3 seconds. Inflicts acid status effect for 5 seconds on all enemies in a 1 tile radius with each enemy in a 2 tile radius having a 50% chance to also be inflicted with the acid status effect. Inflicts effects in a 1 tile radius at point of impact."
        },
        {
            "ID": 2112,
            "HumanReadableName": "FlamingTrebuchet",
            "TowerDescription": "Hurls a super-heated iron orb that will ignite nearby enemies and inflict bludegoning damage in a small radius of its impact",
            "HardData": "Inflicts 15 Bludgeoning damage per projectile with a fire rate of 3 seconds. Inflicts fire status effect for 8 seconds on all enemies in a 1 tile radius with each enemy in a 2 tile radius having a 50% chance to also be inflicted with the fire status effect. Inflicts effects in a 1 tile radius at point of impact."
        },
        {
            "ID": 2176,
            "HumanReadableName": "HolyTrebuchet",
            "TowerDescription": "Hurls a stone wrapped in blessed chains that acts like a normal trebuchet but does extra damage to the undead!",
            "HardData": "Inflicts 15 Holy damage per projectile with a fire rate of 3 seconds.. Inflicts effects in a 1 tile radius at point of impact."
        },
        {
            "ID": 3584,
            "HumanReadableName": "Railgun",
            "TowerDescription": "Launches projectile at high speed that can pierce through several enemies at once!",
            "HardData": "Inflicts up to a total of 100 damage over all enemies in its line of fire."
        },
        {
            "ID": 4096,
            "HumanReadableName": "Water",
            "TowerDescription": "Fires a high pressure jet of water which converts salamanders into lizards, inflicts a small amount of bludgeoning damage, and will put out ignited enemies",
            "HardData": "1 Water damage per water blast."
        },
        {
            "ID": 4160,
            "HumanReadableName": "Steam",
            "TowerDescription": "Generates a cloud of steam that will force enemies moving through it to slow down!",
            "HardData": "Reduces enemy speed by 50% for all enemies in its radius."
        },
        {
            "ID": 4224,
            "HumanReadableName": "HolyWater",
            "TowerDescription": "Fires a stream of blessed water which converts salamanders into lizards, inflicts a small amount of bludgeoning damage, will put out ignited enemies, and inflict holy damage over time.!",
            "HardData": "1 Water damage per water blast."
        },
        {
            "ID": 4672,
            "HumanReadableName": "IceKnife",
            "TowerDescription": "Turns the jet of water into a stream of ice shards that tear into enemies, especially those weak to water in some manner.",
            "HardData": "Inflicts 5 Piercing damage per projectile with a fire rate of 0.3 seconds."
        },
        {
            "ID": 8192,
            "HumanReadableName": "ShotgunBallista",
            "TowerDescription": "Launches 5 smaller javelins, each aiming for a different target if possible. The javelins do slightly less individual damage than a normal javelin.!",
            "HardData": "Each projectile does 5 Piercing damage."
        },
        {
            "ID": 8710,
            "HumanReadableName": "PerpetualShotgun",
            "TowerDescription": "Fires several seeking projectiles at once!",
            "HardData": "Fires 5 projectiles capable of doing up to 35 Piercing damage each. Has a 2 second cool down after all projectiles have expired."
        },
        {
            "ID": 16384,
            "HumanReadableName": "Storm",
            "TowerDescription": "Summons a storm into the sky which will randomly fire bolts of lighting at enemies dealing massive lightning damage!  Requires Activation.",
            "HardData": "50 Electric damage per bolt. 120 second cool down after use"
        },
        {
            "ID": 32768,
            "HumanReadableName": "LightningFence",
            "TowerDescription": "Chains bolts of lightning between towers, enemies passing through take lightning damage and have a chance to be stunned.",
            "HardData": "Inflicts 7 Electric damage with a 10% chance to stun any enemy passing through the lightning."
        },
        {
            "ID": 640,
            "HumanReadableName": "Necrotic",
            "TowerDescription": "Does a large amount of profane damage but heals undead or demonic monsters, such as vampires or ghosts.",
            "HardData": "15 Profane damage per attack with a fire rate of 1 second."
        },
        {
            "ID": 912,
            "HumanReadableName": "DeathRay",
            "TowerDescription": "A long cool down means this tower benefits from selective targeting, however it is not required.  Fires a deadly beam that will cut through any enemies in its path and inflict large amounts of damage.  To aid in this it targets the enemy furthest away from it.",
            "HardData": "Inflicts 4 DeathRay damage every 0.3 seconds over 1.2 seconds to everything in its line of fire. Requires a 2 second cool down after use."
        },
        {
            "ID": 4162,
            "HumanReadableName": "Sonic",
            "TowerDescription": "A directional gong fires a pulsed sound wave that blasts enemies back and stuns them.",
            "HardData": "Inflicts 7 Bludgeoning damage per projectile with a fire rate of 1 seconds."
        },
        {
            "ID": 705,
            "HumanReadableName": "VitalityRipper",
            "TowerDescription": "This tower cannot kill, but will bestow a powerful curse upon enemies ripping their health away until they only have 50% of their health left. Undead and demonic enemies are immune to the effect.",
            "HardData": "1 second active followed by 4.5 seconds inactive while active every 0.25 seconds applies the vitality ripper effect to enemies in range."
        },
        {
            "ID": 1568,
            "HumanReadableName": "Drain",
            "TowerDescription": "Bursts of energy inflict a curse on enemies draining there health slowly and repairing the wall a small amount.",
            "HardData": "1 second active followed by 4.5 seconds inactive while active every 0.25 seconds applies 6 seconds of the drain effect to enemies in range."
        },
        {
            "ID": 642,
            "HumanReadableName": "Miasma",
            "TowerDescription": "A pulse of sickly toxins pumped out into the surrounding air cause lasting weakness in enemies so that they take extra physical damage from attacks already inflicting physical damage.",
            "HardData": "1 second active followed by 4.5 seconds inactive while active every 0.25 seconds applies 10 seconds of the weak effect to enemies in range, inflicting an extra 5 damage if they take damage from a physical damage type and reducing speed by 25%."
        },
        {
            "ID": 65536,
            "HumanReadableName": "StatusRipper",
            "TowerDescription": "Tears into the pain effecting an enemy ripping away any status effects on them and dealing instant damage in exchange for every status removed.",
            "HardData": "Every 0.25 seconds removes all status effects from enemies and inflicts 20 Etheral damage per effect removed."
        },
        {
            "ID": 4800,
            "HumanReadableName": "HolyIceKnife",
            "TowerDescription": "Turns the jet of holy water into a stream of holy ice shards that tear into enemies, especially those weak to water in some manner. Particularly effective against undead and demonic beings.",
            "HardData": "Inflicts 5 Piercing damage or 5 Holy damage (to undead and demonic enemies) per projectile with a fire rate of 0.3 seconds. Inflicts water and holy effects for 10 seconds"
        },
        {
            "ID": 2242,
            "HumanReadableName": "HolyCow",
            "TowerDescription": "Moooo????",
            "HardData": "Inflicts per projectile with a fire rate of 1 seconds."
        },
        {
            "ID": 131072,
            "HumanReadableName": "UNKNOWN",
            "TowerDescription": "This is Filler Text and should not be seen by players!",
            "HardData": "Inflicts per projectile with a fire rate of 1 seconds."
        },
        {
            "ID": 20,
            "HumanReadableName": "CrystalBallista",
            "TowerDescription": "Fire a crystal tipped ballista bolt that will not only pierce an enemy but suppress any special abilites they have for a short time.",
            "HardData": "Inflicts 10 Piercing damage per projectile with a fire rate of 1.25 seconds. Inflicts special suppression status effect for 3 seconds"
        },
        {
            "ID": 82,
            "HumanReadableName": "Bomb",
            "TowerDescription": "The fury of a fireball trapped in a crystal gem and released in a focused blast of crystal shrapnel, heat, and force!  Beware it damaging your walls.",
            "HardData": "Inflicts 15 Bludgeoning damage per projectile with a fire rate of 3 seconds.. Inflicts effects in a 4 tile radius at point of impact."
        },
        {
            "ID": 144,
            "HumanReadableName": "HolyFire",
            "TowerDescription": "The power of the gods is stored in liquid form and then pumped into the air airsoling it into bursts of holy particles, inflicting holy damage to enemies over time",
            "HardData": "1 second active followed by 3.5 seconds inactive while active every 0.25 seconds applies 5 seconds of the drain effect to enemies in range."
        },
        {
            "ID": 1538,
            "HumanReadableName": "Vortex",
            "TowerDescription": "Yanks enemies into a vortex.  The bigger the enemy the more likely they are to be dragged in.  50% chance to Ground flying enemies in its radius!",
            "HardData": ""
        },
        {
            "ID": 1602,
            "HumanReadableName": "StarThrower",
            "TowerDescription": "A minaturized fusion reaction will pull enemies towards it before imploading spectacuraly.  Has a low fire rate but quite devistating when it does.",
            "HardData": "Inflicts 20 Fire damage per projectile with a fire rate of 25 seconds."
        },
        {
            "ID": 2562,
            "HumanReadableName": "MortalCannon",
            "TowerDescription": "Automatically grabs and flings enemies at other enemies, although it is limited by how hardy the enemies are.  Enemies must have a minimum amount of health to be picked up and thrown.  The greater their max health the more damage projectiles will inflict.",
            "HardData": "Grabs a single enemy with health below 25 on impact thrown enemies die and inflict between 25 and 50 Bludegoning damage in a 1 tile radius."
        },
        {
            "ID": 594,
            "HumanReadableName": "Miner",
            "TowerDescription": "Fires a mine that sticks to enemies, multiple mines can stick to one enemy. Shaped charges in the explosive keep it from harming the walls, but reduce its overall destructive power.",
            "HardData": "Fire rate of 2.5 seconds. Launches a mine that will explode dealing 15 Fire and 15 Bludgeoning damage to each enemy in a 2 tile radius as well as launching its own set of mines that will latch onto surviving nearby enemeies"
        },
        {
            "ID": 8464,
            "HumanReadableName": "GatlingLaser",
            "TowerDescription": "Rapidly fire self contained laser bolts into enemies doing less damage per shot, but making up for it in volume.",
            "HardData": "Inflicts 6 Fire damage per projectile with a fire rate of 0.2 seconds."
        },
        {
            "ID": 16512,
            "HumanReadableName": "HolyStorm",
            "TowerDescription": "Summons the wrath of gods upon our foes.  Holy power will strike enemies at random and teach them our wrath!",
            "HardData": "50 Holy damage per bolt. 120 second cool down after use"
        },
        {
            "ID": 48,
            "HumanReadableName": "Geode",
            "TowerDescription": "Crystal outcroppings grow from the ground, block enemy progress and providing useful resources even in their destruction.",
            "HardData": "Has 25 health, on destruction rewards 50 scavenge."
        },
        {
            "ID": 96,
            "HumanReadableName": "Volcano",
            "TowerDescription": "A volcanic growth bubbling up from the ground forming a barrier of cooling lava.  Breaking through it will result in an explosive eruption.",
            "HardData": "Has 25 health, on destruction explodes dealing 0 Physical damage in a 2 tile radius."
        },
        {
            "ID": 2064,
            "HumanReadableName": "CrystalTrebuchet",
            "TowerDescription": "A crystal growth that shatters inflicting damage and suppressing special abilities for a short time",
            "HardData": "Inflicts 15 Bludgeoning damage per projectile with a fire rate of 3 seconds. Inflicts special suppression status effect for 5 seconds on all enemies in a 1 tile radius with each enemy in a 2 tile radius having a 50% chance to also be inflicted with the special suppression status effect. Inflicts effects in a 1 tile radius at point of impact."
        },
        {
            "ID": 4352,
            "HumanReadableName": "Rainbow",
            "TowerDescription": "Projects a fast moving bolt of scattered light suspended in a jet of water that can be used to confuse enemies and make them easier to hit for a short time.",
            "HardData": "Inflicts 1 Water damage, stuns enemies for 2 seconds, and illuminates them for 5 seconds after they are hit"
        },
        {
            "ID": 262144,
            "HumanReadableName": "Whirlwind",
            "TowerDescription": "Fires a micro tornado that flings enemies who get to near it in a random direction damaging them on impact.",
            "HardData": "Every 6 seconds can fire a miniature tornado that flings enemies away from it inflicting 10 damage to each flung enemy."
        },
        {
            "ID": 524288,
            "HumanReadableName": "FingerOfThunderGods",
            "TowerDescription": "The gods of thunder smile down on you and will fire a single power full bolt of lightning from  he sky smiting a foe and dealing damage to those around them.  Only targets enemies marked as current focus.",
            "HardData": "20 second cool down after use. Inflicts 500 Electric damage on all enemies in a 2 tile radius. Will negate any special enemy abilites the instant before impact. Will only fire at enemies marked as focus fire targets."
        }
    ]
}